name: Create

on:
  issues:
    types: [edited, labeled, opened]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    name: Create
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.38.3
      - name: generate UI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          RUN_NUMBER: ${{ github.run_number }}
          ACTOR: ${{ github.actor }}
          NO_COLOR: true
        run: |
          cd vue-preview-ui
          npm i
          deno run -A ../prompts/vue-ui-gen.ts
      - name: Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_XxHbDs2RhY8BQkPfmUQOARhd
          vercel-project-id: Qmd1SNdXw4KXwdbNQ5swM87bAGeyA6zHX9R9sSN2jWpzu6
          working-directory: ./vue-preview-ui/dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: vue-preview-ui/dist
          target-folder: ${{ github.run_number }}
          token: ${{ secrets.PERSONAL_TOKEN }}
