name: Create

on:
  issues:
    types: [edited, labeled, opened]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    name: Create
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.38.3
      - name: generate UI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          RUN_NUMBER: ${{ github.run_number }}
          ACTOR: ${{ github.actor }}
        run: |
          echo "$EVENT_ID"
          deno run -A prompts/vue-ui-gen.ts
      - name: Install and Build
        run: |
          cd vue-preview-ui
          npm i
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: vue-preview-ui/dist
          target-folder: ${{ github.run_number }}
          token: ${{ secrets.PERSONAL_TOKEN }}
