name: autogen-vue-code

on:
  issues:
    types: [edited, labeled, opened]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    name: Create
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.38.3
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            vue-preview-ui/vendor
            vue-preview-ui/node_modules
          key: ${{ runner.os }}-nodeModules-${{ hashFiles('package.json') }}
      - name: Npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          cd vue-preview-ui
          npm i
          deno cache --vendor ../prompts/vue-ui-gen.ts
      - name: generate UI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          RUN_NUMBER: ${{ github.run_number }}
          ACTOR: ${{ github.actor }}
          NO_COLOR: true
        run: cd vue-preview-ui && deno run -A --vendor ../prompts/vue-ui-gen.ts
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: vue-preview-ui/dist
          destination_dir: ${{ github.run_number }}
          github_token: ${{ secrets.PERSONAL_TOKEN }}
